[package]
name = "realm_client"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[dependencies]
realm_server = { version = "0.1", path = "../server" }

log = "0.4"
tarpc = { version = "0.34.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.8", features = ["v4", "fast-rng", "serde"] }
directories-next = "2.0"
tracing-subscriber = "0.3"
async-std = "1.12.0"
once_cell = "1.19.0"
env_logger = "0.11.3"

[dependencies.iced]
git = "https://github.com/iced-rs/iced.git"
rev = "e6d0b3bda5042a1017a5944a5227c97e0ed6caf9"

[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
