name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install sqlx-cli
      run: cargo install sqlx-cli
    - name: Setup Server Database
      run: cd server && sqlx database reset -y
    - name: Setup Auth Database
      run: cd ../auth && sqlx database reset -y
    - name: Build Client
      run: cd ../client && cargo build --verbose
    - name: Build Server
      run: cd ../server && cargo build --verbose
    - name: Build Auth Server
      run: cd ../auth && cargo build --verbose
